### ISSUE TITLE
Please update this theme to work with Firefox v113

### ISSUE THREAD

**Issue by jtlw99** [denizjcan/Firefox-Safari-15-Theme#17]
Please update this theme to work with Firefox v113

**Comment by emslima** [comment]
Hey, I explore and change something here and there, try my UserChrome and tell me if everything is good, then i will send for the orthers here who ask for a fix 

here link:

https://github.com/emslima/emslima/blob/main/userChrome.css

**Comment by jtlw99** [comment]
Bruh i just made my own theme

**Comment by battall** [comment]
> Hey, I explore and change something here and there, try my UserChrome and tell me if everything is good, then i will send for the orthers here who ask for a fix
> 
> here link:
> 
> https://github.com/emslima/emslima/blob/main/userChrome.css

tbh that is really great thanks, except on macos the menu buttons (red green yellow ones) doesnt show. otherwise works expected thanks again
