### ISSUE TITLE
The Safari 15 support mica theme on windows

### ISSUE THREAD

**Issue by linitfor** [denizjcan/Firefox-Safari-15-Theme#2]
Can we have the mica theme support on the Firefox-Safari-15-Theme ?

By the way. The Safari 15 tab have support the tab with color. Will you plan to enable this feature on Firefox-Safari-15-Theme ?

**Comment by linitfor** [comment]
https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-color/
I have found the adaptive tab bar color plugin. This can realize the safari 15 colorful effect.

**Comment by denizjcan** [comment]
> https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-color/ I have found the adaptive tab bar color plugin. This can realize the safari 15 colorful effect.

Thanks for the plugin suggestion. It would be better to use this than Css code, css may break when update comes.



> Can we have the mica theme support on the Firefox-Safari-15-Theme ?
> 
> By the way. The Safari 15 tab have support the tab with color. Will you plan to enable this feature on Firefox-Safari-15-Theme ?

I have added Mica before, but there is a problem of ghost close/minimize/maximize buttons, so I haven't uploaded it to Github. 
I also ran into this issue when I researched other themes using Mica. 
Even if the native buttons are hidden with css, ghost buttons that cannot be clicked appear when MicaForEveryone is activated. If you don't mind giving up the mac style buttons on the left, it is possible to activate the mica theme with the working Windows style buttons.
![buttons](https://user-images.githubusercontent.com/22716602/210780544-66f3acfb-2c77-4070-bf49-08ff791bdb04.png)

**Comment by linitfor** [comment]
Hi denizjcan,

Thanks for your reply. Can you teach me or share the code about how with enable the mica on current use theme?  
I want to try the scheme what the theme look like.

By the way. I have tuning your theme database with the following items.
1. The url input text location a little right to the central of the input box and the more align to the tab page.
2. User self configuration button on right hand side should have some left space.
![圖片](https://user-images.githubusercontent.com/58168507/210918408-47c4847d-6016-48f8-8a63-7052d7f9a68a.png)

3. The url browser display region change to more transparent.
![圖片](https://user-images.githubusercontent.com/58168507/210918778-d5e94b18-c46b-48d1-a2a0-4f3b620f5ef2.png)

Share my tuning source code with you.
[UserChrome.zip](https://github.com/denizjcan/Firefox-Safari-15-Theme/files/10356924/UserChrome.zip)

I have share your web site on the discord which the members who like the windows imitate the macos . ^.^b

The other tuning which not successfully is the tab close button on the left hand side. 
It will more close to mac version. But I still not find the better solution.
![圖片](https://user-images.githubusercontent.com/58168507/210920040-20acf41b-a5b4-4ae2-819a-e81c2d4e0de3.png)

**Comment by linitfor** [comment]
To imitate the close tab on the left hand side like the safari 15 which I mention above.
The following snapshot is my work version.
When the tab is active the close button, the web icon will auto shift right and leave the spacing for the close button.
![image](https://user-images.githubusercontent.com/58168507/210954988-4686138b-d23a-47ec-aa79-f72978231d26.png)


But what I need is the web icon will start red circle on the following snapshot.
![image](https://user-images.githubusercontent.com/58168507/210955131-014f70ee-21b8-4bf2-b14c-dc29f04a2fba.png)

Do you have any idea to implement this feature ?

**Comment by denizjcan** [comment]
Thanks a lot for your edits and sharing with others, it is very valuable to me.

**Comment by denizjcan** [comment]
Thanks a lot for your implementations and sharing with others, it is very valuable to me.

I already deleted the mica codes, I need to find them again but I will try to post them soon 😊

**Comment by denizjcan** [comment]
Unfortunately I don't quite understand snapshot with the red circle.

However, I prepared the necessary code to move the close button to the left on the code you shared and changed the close button image to be close to Safari. 

It looks like this. I moved the tab icon and text completely to the left, when the tab is hovered, the close button appears exactly where the tab icon is. (This is what it looks like in the Safari screenshot you posted as well.)
[safariventura.zip](https://github.com/denizjcan/Firefox-Safari-15-Theme/files/10359398/safariventura.zip)
![1](https://user-images.githubusercontent.com/22716602/210978621-f6632121-355d-4c22-b43f-2a667c879983.png)

I'm not sure exactly how it looks in Safari as I don't have a mac operating system. If not as above, do you want it to be like below?
![2](https://user-images.githubusercontent.com/22716602/210978612-1e190bb2-a142-4eee-b829-5f8954c7f97f.png)

Or do you want the web icon to stay fixed and the close icon to appear in the space in between?
![3(1)](https://user-images.githubusercontent.com/22716602/210986880-f350cc26-2dc3-430b-aaaf-ad8e06797a5c.png)

**Comment by denizjcan** [comment]
If you add this code, the mica theme will be activated.

> #main-window{
  background-color: transparent  !important;
  appearance: -moz-win-borderless-glass !important;
  appearance: -moz-win-glass !important;
}
#navigator-toolbox #TabsToolbar {
  background-image: none !important;
  background-color: transparent !important;
}
#main-window #navigator-toolbox {
  background-color: color-mix(in srgb, field 45%, transparent) !important;
}

**Comment by denizjcan** [comment]
I added the tab close button according to the screenshot you sent, you can download the latest updated version.

**Comment by linitfor** [comment]
Sorry for reply late. I was on the vacation. I will reply you later. Thanks for your appreciation.

**Comment by denizjcan** [comment]
You need to change every "New Tab" text and rewrite it in your language. For example: replace every [label="New Tab"] with [label="Yeni Sekme"] for Turkish.
Because this code searches for tabs with specific name and makes other changes if the text matches.
![1](https://user-images.githubusercontent.com/22716602/211583793-491638b1-6061-4688-bc6f-34b9eb7029fb.png)

However, there is a problem. If many tabs are open, the text "New Tab" label overflows. I'm not sure how to fix this right now 😔.
![2](https://user-images.githubusercontent.com/22716602/211584239-62ca2ad2-b0dd-412d-9f30-4dd5ec4037d6.png)

paste this in userchrome.css


/* this code hides new tab icon */
.tabbrowser-tab[label="Yeni Sekme"] .tab-icon-image {
  opacity: 0;
}

/* this code fixes the "New Tab" text location when its icon hidden */
.tabbrowser-tab[label="Yeni Sekme"] .tab-label:not(:hover) {
  position: relative;
  left: 29px;
  top: 8px;
}

.tabbrowser-tab[label="Yeni Sekme"] .tab-label:hover {
  position: absolute;
  left: 29px;
  top: 8px;
}

/* this code inserts new icon to new tab */
.tabbrowser-tab:not(:hover)[label="Yeni Sekme"] .tab-label-container::before {
  content: "";
  background-image: url('https://img.webme.com/pic/d/denizpl76/icons8-star-50.png');
  background-size: 100%;
  width: 16px;
  height: 16px;
  position: absolute;
  top: 10px;
  left: 8px;
  pointer-events: none;
  opacity: 1;
}

.tabbrowser-tab:hover[label="Yeni Sekme"] .tab-label-container::before {
  content: "";
  background-size: 100%;
  width: 16px;
  height: 16px;
  position: absolute;
  top: 10px;
  left: 8px;
  pointer-events: none;
  opacity: 0;
}

**Comment by denizjcan** [comment]
You can also c
[userContent.zip](https://github.com/denizjcan/Firefox-Safari-15-Theme/files/10383843/userContent.zip)
hange the big logo in the new tab with this code. Paste it in your chrome folder.

**Comment by linitfor** [comment]
Thanks for your reply.

I have import the UserContent.css to UserChrome.css
![圖片](https://user-images.githubusercontent.com/58168507/211615874-04577eb8-a6a2-48c5-b107-6bd131b5e893.png)

and add your suggestion code to the end of the UserChrome.css
But the icons on the tab browser seem not work. Why ? I not understand the meaning ?
![圖片](https://user-images.githubusercontent.com/58168507/211615751-82ccf5d8-2139-4a4a-b526-1039e21a3c04.png)

**Comment by denizjcan** [comment]
You edited the code like this and added it, right? Can you try this?
[code.txt](https://github.com/denizjcan/Firefox-Safari-15-Theme/files/10386836/code.txt)

**Comment by linitfor** [comment]
Thanks a lot. I got it !! ^.^b
![圖片](https://user-images.githubusercontent.com/58168507/211685848-37caa18e-0304-4e27-9b4b-5fad204bf173.png)

**Comment by denizjcan** [comment]
You are welcome ^_^
