### ISSUE TITLE
How to adjust URL bar size?

### ISSUE THREAD

**Issue by kycloudy** [denizjcan/Firefox-Safari-15-Theme#4]
As the title suggests - how do i adjust the URL bar size to make it bigger as well as the search results that pop out when the URL bar is clicked as shown below -
![Screenshot_1](https://user-images.githubusercontent.com/42078899/213354799-9487c5b9-7bc9-4cff-9680-442abf56e981.png)

**Comment by VladCarlsson** [comment]
It would be cool if the address bar will increase it's size when clicked on and go back to normal when not in focus anymore.

**Comment by denizjcan** [comment]
Hello, thanks for your suggestion. I've added the code needed for it to expand when clicked. I'll upload some to the download page 😊

**Comment by kycloudy** [comment]
Just installed the new version and it's perfect! 

Thank you very much :)
