### ISSUE TITLE
Place urlbar inside titlebar of active tab

### ISSUE THREAD

**Issue by asemtahawi** [denizjcan/Firefox-Safari-15-Theme#5]
Is there any chance how the UserChrome.css file can be edited so that the urlbar is placed directly inside the tab label as is the case with safari's compact Tab layout? 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/123258727/213877836-e3d96eed-5ca3-41d7-bd1f-aa71956da3ea.png)

**Comment by denizjcan** [comment]
Hi, this is the biggest shortcoming of the theme, but unfortunately I don't think this is possible with CSS.
